// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Addr():Promise<string>;

export function GetAvailableSkins():Promise<Array<string>>;

export function GetSkinAddress():Promise<string>;

export function InitListener():Promise<Error|number>;

export function SelectedSkin():Promise<string>;

export function Serve():Promise<void>;

export function Serving():Promise<boolean>;

export function SetSkin(arg1:string,arg2:boolean):Promise<void>;

export function Startup():Promise<void>;
