// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Addr() {
  return window['go']['skin']['Service']['Addr']();
}

export function GetAvailableSkins() {
  return window['go']['skin']['Service']['GetAvailableSkins']();
}

export function GetSkinAddress() {
  return window['go']['skin']['Service']['GetSkinAddress']();
}

export function InitListener() {
  return window['go']['skin']['Service']['InitListener']();
}

export function SelectedSkin() {
  return window['go']['skin']['Service']['SelectedSkin']();
}

export function Serve() {
  return window['go']['skin']['Service']['Serve']();
}

export function Serving() {
  return window['go']['skin']['Service']['Serving']();
}

export function SetSkin(arg1, arg2) {
  return window['go']['skin']['Service']['SetSkin'](arg1, arg2);
}

export function Startup() {
  return window['go']['skin']['Service']['Startup']();
}
