package main

import (
	"fmt"
	"os"

	"github.com/zellydev-games/opensplit/command"
)

func main() {
	f, err := os.Create("frontend/src/models/command.ts")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by gencommands; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "export const Command = {")

	commands := []struct {
		Name  string
		Value command.Command
	}{
		{"QUIT", command.QUIT},
		{"NEW", command.NEW},
		{"LOAD", command.LOAD},
		{"EDIT", command.EDIT},
		{"CANCEL", command.CANCEL},
		{"SUBMIT", command.SUBMIT},
		{"CLOSE", command.CLOSE},
		{"RESET", command.RESET},
		{"SAVE", command.SAVE},
		{"SPLIT", command.SPLIT},
		{"UNDO", command.UNDO},
		{"SKIP", command.SKIP},
		{"PAUSE", command.PAUSE},
		{"TOGGLEGLOBAL", command.TOGGLEGLOBAL},
		{"FOCUS", command.FOCUS},
		{"HELLO", command.HELLO},
		{"DONE", command.DONE},
		{"UNDONE", command.UNDONE},
		{"SET_RUNTIME_OFFSET", command.SET_RUNTIME_OFFSET},
		{"CLEAR_RUNTIME_OFFSET", command.CLEAR_RUNTIME_OFFSET},
		{"COMPARISON_LEFT", command.COMPARISON_LEFT},
		{"COMPARISON_RIGHT", command.COMPARISON_RIGHT},
	}

	for _, c := range commands {
		fmt.Fprintf(f, "    %s: %d,\n", c.Name, c.Value)
	}

	fmt.Fprintln(f, "} as const;")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "export type Command = typeof Command[keyof typeof Command];")
}
