// tools/gencommands/main.go
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
)

type command struct {
	Name  string
	Value int
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	src := filepath.Join(root, "command", "commands.go")

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, src, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}

	var commands []command

	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}

		value := 0

		for _, spec := range gen.Specs {
			vs := spec.(*ast.ValueSpec)

			if len(vs.Values) != 0 {
				if ident, ok := vs.Values[0].(*ast.Ident); ok && ident.Name == "iota" {
					value = 0
				}
			}

			for _, name := range vs.Names {
				commands = append(commands, command{
					Name:  name.Name,
					Value: value,
				})
				value++
			}
		}
	}

	var out bytes.Buffer

	fmt.Fprintln(&out, "// Code generated by tools/gencommands. DO NOT EDIT.")
	fmt.Fprintln(&out)

	fmt.Fprintln(&out, "export const Command = {")

	for _, c := range commands {
		fmt.Fprintf(&out, "\t%s: %d,\n", c.Name, c.Value)
	}

	fmt.Fprintln(&out, "} as const;")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "export type Command = typeof Command[keyof typeof Command];")

	dst := filepath.Join(root, "frontend", "src", "models", "command.ts")

	if existing, err := os.ReadFile(dst); err == nil && bytes.Equal(existing, out.Bytes()) {
		return
	}

	if err := os.WriteFile(dst, out.Bytes(), 0644); err != nil {
		panic(err)
	}
}
